language: ruby
env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_FREE_MIN=200000
rvm:
  - 1.9.3
  - jruby-19mode
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
script: "bundle exec rspec spec"
